[package]
name = "observer"
version = "0.2.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
sha1 = "0.10"
log = "0.4.29"
env_logger = "0.11.9"
uuid = { version = "=1.11.0", features = ["v4"] }
windows-sys = { workspace = true }
